### ISSUE TITLE
I believe the Weather forecast API isn't working

### ISSUE THREAD

**Issue by icebelly29** [louisefindlay23/auroraspotter#12]
I would love to take a look at the issue and resolve it

**Comment by louisefindlay23** [comment]
Hi, @icebelly29. Have you enabled location permissions? I tested it and it seems to be working fine. Do you have a screenshot of the issue?

**Comment by icebelly29** [comment]
@louisefindlay23 I'm sorry, I didn't turn on location when I checked it the first time😖
